package com.semo.keyboard.domain.logic

/**
 * إيموجي مقترحة بشريط الاقتراحات (مثل QuickType بآيفون): كلمة مثل "love" أو "حب" تقترح ❤️.
 * قاموس صغير ثابت بالعربي والإنكليزي؛ المطابقة على الكلمة كاملة فقط كي لا تظهر اقتراحات مزعجة.
 */
object EmojiSuggestions {

    private val map: Map<String, String> = buildMap {
        fun add(emoji: String, vararg words: String) {
            for (w in words) put(w, emoji)
        }
        // ---- English ----
        add("❤️", "love", "heart", "luv", "loved", "loves")
        add("😂", "lol", "haha", "hahaha", "funny", "lmao")
        add("😊", "happy", "smile", "glad", "pleased")
        add("😍", "adore", "gorgeous", "wow")
        add("😢", "sad", "cry", "crying", "sorry")
        add("😭", "sob", "tears")
        add("😡", "angry", "mad", "furious")
        add("😴", "sleep", "sleepy", "tired", "goodnight")
        add("🤔", "think", "thinking", "hmm", "maybe")
        add("😎", "cool", "awesome", "swag")
        add("😘", "kiss", "kisses", "xoxo")
        add("😱", "scared", "shocked", "omg")
        add("🤒", "sick", "ill", "fever")
        add("🥳", "party", "celebrate", "birthday", "congrats", "congratulations")
        add("🎉", "hooray", "yay")
        add("👍", "ok", "okay", "good", "great", "thanks", "thank", "yes", "agree")
        add("👎", "bad", "no", "dislike")
        add("👋", "hi", "hello", "hey", "bye", "goodbye")
        add("🙏", "please", "pray", "prayer", "grateful", "blessed")
        add("👏", "bravo", "clap", "applause", "congrat")
        add("💪", "strong", "gym", "workout", "muscle")
        add("🔥", "fire", "hot", "lit")
        add("⭐", "star", "stars")
        add("☀️", "sun", "sunny", "summer")
        add("🌧️", "rain", "rainy")
        add("❄️", "snow", "cold", "winter")
        add("🌙", "moon", "night")
        add("🌹", "rose", "flower", "flowers")
        add("🎂", "cake")
        add("🍕", "pizza")
        add("🍔", "burger", "hamburger")
        add("☕", "coffee", "tea")
        add("🍎", "apple")
        add("🐶", "dog", "puppy")
        add("🐱", "cat", "kitten")
        add("🚗", "car", "drive", "driving")
        add("✈️", "flight", "plane", "travel", "airport")
        add("🏠", "home", "house")
        add("📱", "phone", "mobile", "call")
        add("💻", "laptop", "computer", "work")
        add("📚", "book", "books", "study", "exam")
        add("🎵", "music", "song", "songs")
        add("⚽", "football", "soccer", "goal")
        add("💰", "money", "cash", "rich", "salary")
        add("🎁", "gift", "present")
        add("💔", "heartbroken", "breakup", "broken")
        add("🙄", "whatever", "seriously")
        add("🤝", "deal", "agreement", "handshake")
        add("🕌", "mosque", "ramadan", "eid")
        // ---- العربية ----
        add("❤️", "حب", "حبي", "قلب", "قلبي", "احبك", "أحبك", "بحبك", "عشق", "حبيبي", "حبيبتي")
        add("😂", "ههه", "هههه", "ضحك", "مضحك", "نكتة")
        add("😊", "سعيد", "سعيدة", "فرح", "فرحان", "ابتسامة", "مبسوط")
        add("😢", "حزين", "حزينة", "زعلان", "زعلانة", "بكاء", "اسف", "آسف", "آسفة")
        add("😭", "ابكي", "دموع")
        add("😡", "غاضب", "غضب", "زعلت", "عصبي")
        add("😴", "نوم", "نعسان", "نعسانة", "تعبان", "تعبانة", "تصبح", "تصبحون")
        add("🤔", "تفكير", "افكر", "أفكر", "ممكن", "يمكن")
        add("😎", "رائع", "جامد", "ممتاز")
        add("😘", "بوسة", "قبلة", "تحياتي")
        add("😱", "خايف", "خوف", "صدمة")
        add("🤒", "مريض", "مريضة", "حرارة", "مرض")
        add("🥳", "حفلة", "مبروك", "عيد", "ميلاد", "تهنئة")
        add("🎉", "يلا", "هيا")
        add("👍", "تمام", "حسنا", "حسناً", "اوكي", "موافق", "ماشي", "نعم", "اي", "أجل", "شكرا", "شكراً", "يسلمو", "جيد")
        add("👎", "سيء", "لا", "مو")
        add("👋", "اهلا", "أهلا", "أهلاً", "مرحبا", "مرحباً", "هلا", "سلام", "وداعا", "باي", "مع السلامة")
        add("🙏", "رجاء", "ارجوك", "أرجوك", "دعاء", "ادعو", "ادعي", "الله", "يارب", "اللهم", "بارك")
        add("👏", "برافو", "تصفيق", "احسنت", "أحسنت")
        add("💪", "قوي", "نادي", "رياضة", "عضلات")
        add("🔥", "نار", "حار", "حريق")
        add("⭐", "نجمة", "نجوم")
        add("☀️", "شمس", "صيف", "مشمس")
        add("🌧️", "مطر", "ممطر", "شتاء")
        add("🌙", "قمر", "ليل", "ليلة")
        add("🌹", "وردة", "ورد", "زهرة", "زهور")
        add("🎂", "كعكة", "تورتة")
        add("🍕", "بيتزا")
        add("🍔", "برجر")
        add("☕", "قهوة", "شاي")
        add("🐶", "كلب")
        add("🐱", "قطة", "قط")
        add("🚗", "سيارة", "قيادة")
        add("✈️", "طائرة", "سفر", "مطار", "رحلة")
        add("🏠", "بيت", "منزل", "دار")
        add("📱", "جوال", "هاتف", "موبايل", "اتصال")
        add("💻", "لابتوب", "كمبيوتر", "شغل", "عمل")
        add("📚", "كتاب", "كتب", "دراسة", "امتحان", "مذاكرة")
        add("🎵", "موسيقى", "اغنية", "أغنية", "اغاني")
        add("⚽", "كرة", "مباراة", "هدف")
        add("💰", "مال", "فلوس", "نقود", "راتب")
        add("🎁", "هدية", "هدايا")
        add("💔", "فراق", "كسر")
        add("🕌", "مسجد", "جامع", "رمضان", "صلاة", "جمعة")
    }

    /** إيموجي مقترحة للكلمة (مطابقة كاملة بلا اعتبار لحالة الأحرف) أو null */
    fun forWord(word: String): String? {
        val w = word.trim()
        if (w.length < 2) return null
        return map[w.lowercase()]
    }
}
